{{- $browserless := index .Values "browserless-chromium" -}}
{{- if and $browserless.enabled $browserless.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "browserless-chromium.fullname" . }}
  labels:
    {{- include "browserless-chromium.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "browserless-chromium.fullname" . }}
  minReplicas: {{ $browserless.autoscaling.minReplicas }}
  maxReplicas: {{ $browserless.autoscaling.maxReplicas }}
  metrics:
    {{- if $browserless.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $browserless.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $browserless.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $browserless.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
