{{- $browserless := index .Values "browserless-chromium" -}}
{{- if $browserless.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "browserless-chromium.fullname" . }}
  labels:
    {{- include "browserless-chromium.labels" . | nindent 4 }}
spec:
  {{- if not $browserless.autoscaling.enabled }}
  replicas: {{ $browserless.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "browserless-chromium.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $browserless.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "browserless-chromium.labels" . | nindent 8 }}
        {{- with $browserless.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $browserless.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lobehub.serviceAccountName" . }}
      {{- with $browserless.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "browserless-chromium.name" . }}
          {{- with $browserless.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $browserless.image.repository }}:{{ $browserless.image.tag }}"
          imagePullPolicy: {{ $browserless.image.pullPolicy }}
          env:
            {{- range $key, $val := $browserless.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          ports:
            - name: ws
              containerPort: {{ $browserless.service.port }}
              protocol: TCP
          {{- with $browserless.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $browserless.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $browserless.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $browserless.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $browserless.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $browserless.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $browserless.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $browserless.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
