apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "miaospeed.fullname" . }}-secret
  labels:
    {{- include "miaospeed.labels" . | nindent 4 }}
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

