{{- if .Values.playwright.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "playwright.fullname" . }}
  labels:
    {{- include "playwright.labels" . | nindent 4 }}
spec:
  type: {{ .Values.playwright.service.type }}
  ports:
    - port: {{ .Values.playwright.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "playwright.selectorLabels" . | nindent 4 }}
{{- end }}
