apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quote-bot.fullname" . }}-secret
  labels:
    {{- include "quote-bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
