apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quote-bot.fullname" . }}-secret
  labels:
    {{- include "quote-bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- if ne $key "MONGODB_URI" }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
  {{- end }}
  MONGODB_URI: {{ include "quote-bot.mongodbUri" . | b64enc | quote }}
