{{- $backend := index .Values "hedgedoc-backend" -}}
{{- if and $backend.enabled $backend.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "hedgedoc-backend.fullname" . }}-data
  labels:
    {{- include "hedgedoc-backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $backend.persistence.accessMode }}
  resources:
    requests:
      storage: {{ $backend.persistence.size }}
  {{- if $backend.persistence.storageClass }}
  storageClassName: {{ $backend.persistence.storageClass }}
  {{- end }}
{{- end }}
