{{- $backend := index .Values "hedgedoc-backend" -}}
{{- if $backend.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hedgedoc-backend.fullname" . }}-secret
  labels:
    {{- include "hedgedoc-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := $backend.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
