apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}-secret
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
