{{- if .Values.neo4j.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cognee.neo4jFullname" . }}
  labels:
    {{- include "cognee.neo4jLabels" . | nindent 4 }}
spec:
  type: {{ .Values.neo4j.service.type }}
  ports:
    - name: http
      port: {{ .Values.neo4j.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: bolt
      port: {{ .Values.neo4j.service.boltPort }}
      targetPort: bolt
      protocol: TCP
  selector:
    {{- include "cognee.neo4jSelectorLabels" . | nindent 4 }}
{{- end }}
