{{- if .Values.chromadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cognee.chromadbFullname" . }}
  labels:
    {{- include "cognee.chromadbLabels" . | nindent 4 }}
spec:
  type: {{ .Values.chromadb.service.type }}
  ports:
    - name: http
      port: {{ .Values.chromadb.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "cognee.chromadbSelectorLabels" . | nindent 4 }}
{{- end }}
