{{- if .Values.frpc.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frp.fullname" . }}-config-frpc
  labels:
    {{- include "frpc.labels" . | nindent 4 }}
data:
  frpc.toml: |
    {{ .Values.frpc.config | indent 4 }}
{{- end }}