apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headplane.fullname" . }}-config
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.global.headplaneConfig  | default .Values.headplaneConfig  | toYaml | nindent 4 }}