apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headplane.fullname" . }}-config
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}