apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xray.fullname" . }}-auth
  labels:
    {{- include "xray.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (printf "%s-auth" (include "xray.fullname" .))) | default dict }}
  {{- $secretData := $secretObj.data | default dict }}

  {{- range .Values.xrayConfig.inbounds }}
    {{- $inboundTag := .tag }}
    {{- $settings := .settings | default dict }}
    {{- if $settings }}
      
      {{- /* 计算长度 */ -}}
      {{- $method := $settings.method | default "2022-blake3-aes-128-gcm" }}
      {{- $keyLen := 16 }}
      {{- if or (contains "256" $method) (contains "chacha20" $method) }}
        {{- $keyLen = 32 }}
      {{- end }}

      {{- /* 1. 生成服务端密码 */ -}}
      {{- $srvKeyName := printf "%s-password" $inboundTag }}
      {{- $srvPass := "" }}
      {{- if and $settings.password (ne $settings.password "auto") }}
        {{- $srvPass = $settings.password }}
      {{- else if hasKey $secretData $srvKeyName }}
        {{- $srvPass = index $secretData $srvKeyName | b64dec }}
      {{- else }}
        {{- $srvPass = randAlphaNum $keyLen | b64enc }}
      {{- end }}
  {{ $srvKeyName }}: {{ $srvPass | quote }}

      {{- /* 2. 生成客户端密码 */ -}}
      {{- if $settings.clients }}
        {{- range $index, $client := $settings.clients }}
          {{- $clientKeyName := printf "%s-client-%d-password" $inboundTag $index }}
          {{- $cliPass := "" }}
          {{- if and $client.password (ne $client.password "auto") }}
            {{- $cliPass = $client.password }}
          {{- else if hasKey $secretData $clientKeyName }}
            {{- $cliPass = index $secretData $clientKeyName | b64dec }}
          {{- else }}
            {{- $cliPass = randAlphaNum $keyLen | b64enc }}
          {{- end }}
  {{ $clientKeyName }}: {{ $cliPass | quote }}
        {{- end }}
      {{- end }}

    {{- end }}
  {{- end }}