apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headscale.fullname" . }}-config
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $global := get .Values "global" | default dict }}
    {{- $config := get $global "headscaleConfig" | default .Values.headscaleConfig }}
    {{- $config | toYaml | nindent 4 }}
