apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "koipy.fullname" . }}-config
  labels:
    {{- include "koipy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.koipyConfig  | toYaml | nindent 4 }}