{{- $secretName := printf "%s-secret" (include "tabby-web.fullname" .) -}}

{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "tabby-web.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ if $val }}
       {{- $val | b64enc | quote -}}
  {{- else if (hasKey $secretData $key) }}
    {{- index $secretData $key -}}
  {{- else }}
    {{- randAlphaNum 24 | b64enc | quote -}}
  {{- end }}
  {{- end }}