{{- $secretName := printf "%s-secret" (include "substore.fullname" .) -}}

{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "substore.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ if $val }}
    {{- /* 鐗规畩澶勭悊 SUB_STORE_FRONTEND_BACKEND_PATH */ -}}
    {{- if eq $key "SUB_STORE_FRONTEND_BACKEND_PATH" -}}
       {{- printf "/%s" (trimPrefix "/" $val) | b64enc | quote -}}
    {{- else -}}
       {{- $val | b64enc | quote -}}
    {{- end -}}
  {{- else if (hasKey $secretData $key) }}
    {{- index $secretData $key -}}
  {{- else }}
    {{- randAlphaNum 24 | b64enc | quote -}}
  {{- end }}
  {{- end }}

