{{- $secretName := printf "%s-secret" (include "substore.fullname" .) -}}

{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "substore.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ if $val }}
    {{- /* A. 如果 values.yaml 中用户填了值，优先使用用户的值 (需 base64) */ -}}
    {{- $val | b64enc | quote -}}
  {{- else if (hasKey $secretData $key) }}
    {{- /* B. 如果集群里已有旧值，使用旧值 (已经是 base64，直接用) */ -}}
    {{- index $secretData $key -}}
  {{- else }}
    {{- /* C. 既没填也没旧值，生成随机新值 (需 base64) */ -}}
    {{- randAlphaNum 24 | b64enc | quote -}}
  {{- end }}
  {{- end }}