apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "substore.fullname" . }}-config
  labels:
    {{- include "substore.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}