apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns-server.fullname" . }}
  labels:
    {{- include "dns-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.dohPort }}
      targetPort: doh
      protocol: TCP
      name: doh
  selector:
    {{- include "dns-server.selectorLabels" . | nindent 4 }}

