apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automem.fullname" . }}-config
  labels:
    {{- include "automem.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ tpl ($val | toString) $ | quote }}
  {{- end }}
