apiVersion: v1
kind: Secret
metadata:
  name: {{ include "automem.fullname" . }}-secret
  labels:
    {{- include "automem.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
  {{- end }}
