{{- if .Values.graphViewer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "automem.fullname" . }}-viewer
  labels:
    {{- include "automem.graphViewerLabels" . | nindent 4 }}
  {{- with .Values.graphViewer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.graphViewer.service.type }}
  ports:
    - port: {{ .Values.graphViewer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.graphViewer.service.type "NodePort" }}
      nodePort: {{ .Values.graphViewer.service.nodePort }}
      {{- end }}
  selector:
    {{- include "automem.graphViewerSelectorLabels" . | nindent 4 }}
{{- end }}
