apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "next-ai-draw-io.fullname" . }}-config
  labels:
    {{- include "next-ai-draw-io.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}