apiVersion: v2
name: quote-bot
description: Telegram quote bot with quote-api dependency

type: application

# Chart version
version: 0.0.7

# Application version
appVersion: "latest"

dependencies:
  - name: valkey
    version: "0.9.3"
    repository: https://valkey-io.github.io/valkey-helm
    condition: valkey.enabled
  - name: quote-api
    version: "0.0.1"
    repository: https://sakullla.github.io/helm-charts
    condition: quote-api.enabled
