apiVersion: v2
name: quote-bot
description: Telegram quote bot with quote-api dependency

type: application

# Chart version
version: 0.0.1

# Application version
appVersion: "latest"

dependencies:
  - name: quote-api
    version: "0.0.1"
    repository: "file://../quote-api"
    condition: quote-api.enabled
