apiVersion: v2
name: quote-bot
description: Telegram quote bot with quote-api dependency

type: application

# Chart version
version: 0.0.2

# Application version
appVersion: "latest"

dependencies:
  - name: redis
    version: "20.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: quote-api
    version: "0.0.1"
    repository: https://sakullla.github.io/helm-charts
    condition: quote-api.enabled
