apiVersion: v1
kind: Service
metadata:
  name: {{ include "browserless-chromium.fullname" . }}
  labels:
    {{- include "browserless-chromium.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "browserless-chromium.selectorLabels" . | nindent 4 }}
