apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quote-api.fullname" . }}-secret
  labels:
    {{- include "quote-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
